/**
 * Regression test — P0-1: reconciliação contra transação manual não cria duplicata.
 *
 * Falha ANTES da correção: processResolvedImportBatch não existe como export, ou
 * sempre envia tudo pelo caminho de import (LedgerService), criando duplicata.
 * Passa APÓS a correção: transações com _reconciled=true e ID Firestore real são
 * encaminhadas para updateTransaction, nunca para onImportTransactions.
 */
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { toCentavos } from '../../../shared/types/money';
import type { Centavos } from '../../../shared/types/money';

// ─── Mocks hoisted (executam antes dos vi.mock) ───────────────────────────────
const { mockUpdateTransaction, mockLogTransactionHistory } = vi.hoisted(() => ({
  mockUpdateTransaction:     vi.fn().mockResolvedValue(undefined),
  mockLogTransactionHistory: vi.fn().mockResolvedValue(undefined),
}));

// Mocked antes da importação do módulo sob teste
vi.mock('../../../shared/services/FirestoreService', () => ({
  FirestoreService: { updateTransaction: mockUpdateTransaction },
}));

vi.mock('../../../shared/services/AuditService', () => ({
  AuditService: { logTransactionHistory: mockLogTransactionHistory },
}));

// Firebase — necessário para módulos no chain de importação do ImportButton
vi.mock('firebase/firestore', () => ({
  collection:      vi.fn(),
  doc:             vi.fn(),
  updateDoc:       vi.fn(),
  addDoc:          vi.fn(),
  getDoc:          vi.fn(),
  serverTimestamp: vi.fn(() => ({ _serverTimestamp: true })),
  deleteField:     vi.fn(() => ({ _deleteField: true })),
}));

vi.mock('../../../shared/api/firebase/index', () => ({ db: { _isMock: true } }));

// Módulos com side effects que não são exercidos pelo path de teste
vi.mock('../../../shared/lib/useParserWorker', () => ({ useParserWorker: vi.fn() }));
vi.mock('../../../utils/aiCategorize', () => ({
  batchCategorizeDescriptions: vi.fn(),
  categorizeTransaction:       vi.fn(),
}));

// ─── Import do alvo (após todos os mocks) ─────────────────────────────────────
import { processResolvedImportBatch } from '../ImportButton';

// ─── Helper ───────────────────────────────────────────────────────────────────
type TxInput = {
  id:             string;
  description:    string;
  value_cents:    Centavos;
  type:           'saida' | 'entrada';
  category:       string;
  date:           string;
  source?:        'csv' | 'ofx' | 'pdf' | 'manual';
  schemaVersion?: number;
  _reconciled?:   boolean;
  _mergedWith?:   string;
};

function makeTx(overrides: Partial<TxInput> = {}): TxInput {
  return {
    id:           '__temp_test_default',
    description:  'Pagamento de teste',
    value_cents:  toCentavos(1500) as Centavos,
    type:         'saida',
    category:     'Moradia',
    date:         '2024-03-15',
    source:       'manual',
    schemaVersion: 2,
    ...overrides,
  };
}

// ─── Testes ───────────────────────────────────────────────────────────────────
describe('processResolvedImportBatch — roteamento de reconciliação', () => {
  const uid = 'uid-test-user';

  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('transação reconciliada com ID Firestore existente: chama updateTransaction, NÃO chama onImportTransactions', async () => {
    const existingDocId = 'firestoreAutoGeneratedId123';
    const reconciledTx  = makeTx({ id: existingDocId, _reconciled: true, _mergedWith: 'imported-hash-abc' });
    const onImport      = vi.fn().mockResolvedValue({ added: 0, duplicates: 0 });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const result = await processResolvedImportBatch(uid, [reconciledTx] as any, onImport);

    // Deve atualizar o doc existente — sem criar doc novo no caminho hash
    expect(mockUpdateTransaction).toHaveBeenCalledOnce();
    expect(mockUpdateTransaction).toHaveBeenCalledWith(
      uid,
      existingDocId,
      expect.objectContaining({ description: 'Pagamento de teste', category: 'Moradia' }),
    );

    // onImportTransactions → LedgerService NÃO deve ser acionado para este tx
    expect(onImport).not.toHaveBeenCalled();

    expect(result.reconciledCount).toBe(1);
    expect(result.added).toBe(0);
    expect(result.validCount).toBe(1);
  });

  it('transação SEM _reconciled: segue o caminho de import normal (LedgerService)', async () => {
    const newTx   = makeTx({ id: '__temp_123_abc' });
    const onImport = vi.fn().mockResolvedValue({ added: 1, duplicates: 0 });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const result = await processResolvedImportBatch(uid, [newTx] as any, onImport);

    expect(mockUpdateTransaction).not.toHaveBeenCalled();
    expect(onImport).toHaveBeenCalledOnce();
    expect(result.added).toBe(1);
    expect(result.reconciledCount).toBe(0);
  });

  it('mistura de reconciliada + nova: sem duplicata, ambas as rotas corretas', async () => {
    const existingId   = 'manualFirestoreDocId';
    const reconciledTx = makeTx({ id: existingId, _reconciled: true });
    const newTx        = makeTx({ id: '__temp_999_xyz', description: 'Nova importação' });
    const onImport     = vi.fn().mockResolvedValue({ added: 1, duplicates: 0 });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const result = await processResolvedImportBatch(uid, [reconciledTx, newTx] as any, onImport);

    // Existente: update no ID original
    expect(mockUpdateTransaction).toHaveBeenCalledOnce();
    expect(mockUpdateTransaction).toHaveBeenCalledWith(uid, existingId, expect.any(Object));

    // Nova: enviada para import (LedgerService)
    expect(onImport).toHaveBeenCalledOnce();

    expect(result.reconciledCount).toBe(1);
    expect(result.added).toBe(1);
    expect(result.validCount).toBe(2);
  });

  it('_reconciled=true com ID __temp_: trata como nova import (temp = ainda não confirmado no Firestore)', async () => {
    const tempTx   = makeTx({ id: '__temp_456_def', _reconciled: true });
    const onImport = vi.fn().mockResolvedValue({ added: 1, duplicates: 0 });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await processResolvedImportBatch(uid, [tempTx] as any, onImport);

    // ID temporário NÃO deve acionar update
    expect(mockUpdateTransaction).not.toHaveBeenCalled();
    expect(onImport).toHaveBeenCalledOnce();
  });

  it('grava auditoria UPDATE (não IMPORT_TRANSACTION) para transação reconciliada', async () => {
    const existingId   = 'auditTestDocId';
    const reconciledTx = makeTx({ id: existingId, _reconciled: true });
    const onImport     = vi.fn();

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await processResolvedImportBatch(uid, [reconciledTx] as any, onImport);

    expect(mockLogTransactionHistory).toHaveBeenCalledOnce();
    expect(mockLogTransactionHistory).toHaveBeenCalledWith(
      uid,
      existingId,
      expect.objectContaining({ action: 'UPDATE', txId: existingId, origin: 'reconcile' }),
    );
  });

  it('sem uid: não chama updateTransaction nem lança erro', async () => {
    const reconciledTx = makeTx({ id: 'someDocId', _reconciled: true });
    const onImport     = vi.fn().mockResolvedValue({ added: 0 });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await expect(processResolvedImportBatch(undefined, [reconciledTx] as any, onImport)).resolves.not.toThrow();
    expect(mockUpdateTransaction).not.toHaveBeenCalled();
  });
});
