/**
 * Regression test — P0-1: reconciliação contra transação manual não cria duplicata.
 *
 * Falha ANTES da correção: processResolvedImportBatch não existe como export, ou
 * sempre envia tudo pelo caminho de import (LedgerService), criando duplicata.
 * Passa APÓS a correção: transações com _reconciled=true e ID Firestore real são
 * encaminhadas para updateTransaction, nunca para onImportTransactions.
 */
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { toCentavos } from '../../../shared/types/money';
import type { Centavos } from '../../../shared/types/money';
import type { Transaction } from '../../../shared/types/transaction';

// ─── Mocks hoisted (executam antes dos vi.mock) ───────────────────────────────
const { mockUpdateTransactionWithHistory } = vi.hoisted(() => ({
  mockUpdateTransactionWithHistory: vi.fn().mockResolvedValue(undefined),
}));

// Mocked antes da importação do módulo sob teste
vi.mock('../../../shared/services/FirestoreService', () => ({
  FirestoreService: { updateTransactionWithHistory: mockUpdateTransactionWithHistory },
}));

// Firebase — necessário para módulos no chain de importação do ImportButton
vi.mock('firebase/firestore', () => ({
  collection:      vi.fn(),
  doc:             vi.fn(),
  updateDoc:       vi.fn(),
  addDoc:          vi.fn(),
  getDoc:          vi.fn(),
  serverTimestamp: vi.fn(() => ({ _serverTimestamp: true })),
  deleteField:     vi.fn(() => ({ _deleteField: true })),
}));

vi.mock('../../../shared/api/firebase/index', () => ({ db: { _isMock: true }, functions: { _isMock: true } }));

// Módulos com side effects que não são exercidos pelo path de teste
vi.mock('../../../shared/lib/useParserWorker', () => ({ useParserWorker: vi.fn() }));
vi.mock('../../../utils/aiCategorize', () => ({
  batchCategorizeDescriptions: vi.fn(),
  categorizeTransaction:       vi.fn(),
}));

// ─── Import do alvo (após todos os mocks) ─────────────────────────────────────
import { processResolvedImportBatch } from '../ImportButton';

// ─── Helper ───────────────────────────────────────────────────────────────────
type TxInput = {
  id:             string;
  description:    string;
  value_cents:    Centavos;
  type:           'saida' | 'entrada';
  category:       string;
  date:           string;
  source?:        'csv' | 'ofx' | 'pdf' | 'manual';
  fitId?:         string | null;
  schemaVersion?: number;
  _reconciled?:   boolean;
  _mergedWith?:   string;
};

function makeTx(overrides: Partial<TxInput> = {}): TxInput {
  return {
    id:           '__temp_test_default',
    description:  'Pagamento de teste',
    value_cents:  toCentavos(1500) as Centavos,
    type:         'saida',
    category:     'Moradia',
    date:         '2024-03-15',
    source:       'manual',
    schemaVersion: 2,
    ...overrides,
  };
}

// ─── Testes ───────────────────────────────────────────────────────────────────
describe('processResolvedImportBatch — roteamento de reconciliação', () => {
  const uid = 'uid-test-user';

  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('transação reconciliada com ID Firestore existente: chama updateTransactionWithHistory, NÃO chama onImportTransactions', async () => {
    const existingDocId = 'firestoreAutoGeneratedId123';
    const reconciledTx  = makeTx({ id: existingDocId, _reconciled: true, _mergedWith: 'imported-hash-abc' });
    const onImport      = vi.fn().mockResolvedValue({ added: 0, duplicates: 0 });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const result = await processResolvedImportBatch(uid, [reconciledTx] as any, onImport);

    // Deve atualizar o doc existente atomicamente (batch + history) — sem criar doc novo no caminho hash
    expect(mockUpdateTransactionWithHistory).toHaveBeenCalledOnce();
    expect(mockUpdateTransactionWithHistory).toHaveBeenCalledWith(
      uid,
      existingDocId,
      expect.objectContaining({
        description:          'Pagamento de teste',
        category:             'Moradia',
        reconciliationStatus: 'reconciled',
        reconciliationSource: 'import',
        reconciledAt:         { _serverTimestamp: true },
        reconciledBy:         uid,
      }),
      expect.objectContaining({ origin: 'reconcile' }),
    );

    // onImportTransactions → LedgerService NÃO deve ser acionado para este tx
    expect(onImport).not.toHaveBeenCalled();

    expect(result.reconciledCount).toBe(1);
    expect(result.added).toBe(0);
    expect(result.validCount).toBe(1);
  });

  it('transação SEM _reconciled: segue o caminho de import normal (LedgerService)', async () => {
    const newTx   = makeTx({ id: '__temp_123_abc' });
    const onImport = vi.fn().mockResolvedValue({ added: 1, duplicates: 0 });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const result = await processResolvedImportBatch(uid, [newTx] as any, onImport);

    expect(mockUpdateTransactionWithHistory).not.toHaveBeenCalled();
    expect(onImport).toHaveBeenCalledOnce();
    const importedPayload = onImport.mock.calls[0]?.[0]?.[0] as Record<string, unknown>;
    expect(importedPayload).not.toHaveProperty('reconciliationStatus');
    expect(importedPayload).not.toHaveProperty('reconciliationSource');
    expect(importedPayload).not.toHaveProperty('reconciledAt');
    expect(importedPayload).not.toHaveProperty('reconciledBy');
    expect(result.added).toBe(1);
    expect(result.reconciledCount).toBe(0);
  });

  it('mistura de reconciliada + nova: sem duplicata, ambas as rotas corretas', async () => {
    const existingId   = 'manualFirestoreDocId';
    const reconciledTx = makeTx({ id: existingId, _reconciled: true });
    const newTx        = makeTx({ id: '__temp_999_xyz', description: 'Nova importação' });
    const onImport     = vi.fn().mockResolvedValue({ added: 1, duplicates: 0 });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const result = await processResolvedImportBatch(uid, [reconciledTx, newTx] as any, onImport);

    // Existente: update atômico no ID original (batch + history)
    expect(mockUpdateTransactionWithHistory).toHaveBeenCalledOnce();
    expect(mockUpdateTransactionWithHistory).toHaveBeenCalledWith(uid, existingId, expect.any(Object), expect.any(Object));

    // Nova: enviada para import (LedgerService)
    expect(onImport).toHaveBeenCalledOnce();

    expect(result.reconciledCount).toBe(1);
    expect(result.added).toBe(1);
    expect(result.validCount).toBe(2);
  });

  it('_reconciled=true com ID __temp_: trata como nova import (temp = ainda não confirmado no Firestore)', async () => {
    const tempTx   = makeTx({ id: '__temp_456_def', _reconciled: true });
    const onImport = vi.fn().mockResolvedValue({ added: 1, duplicates: 0 });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await processResolvedImportBatch(uid, [tempTx] as any, onImport);

    // ID temporário NÃO deve acionar update
    expect(mockUpdateTransactionWithHistory).not.toHaveBeenCalled();
    expect(onImport).toHaveBeenCalledOnce();
  });

  it('grava history UPDATE atômico (não IMPORT_TRANSACTION) para transação reconciliada', async () => {
    const existingId   = 'auditTestDocId';
    const reconciledTx = makeTx({ id: existingId, _reconciled: true });
    const onImport     = vi.fn();

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await processResolvedImportBatch(uid, [reconciledTx] as any, onImport);

    expect(mockUpdateTransactionWithHistory).toHaveBeenCalledOnce();
    expect(mockUpdateTransactionWithHistory).toHaveBeenCalledWith(
      uid,
      existingId,
      expect.any(Object),
      expect.objectContaining({ origin: 'reconcile' }),
    );
  });

  it('audita todos os campos alterados da conciliação com before/after parciais', async () => {
    const existingId = 'auditDeltaDocId';
    const beforeTx: Transaction = {
      id:            existingId,
      description:   'Compra manual',
      value:         120,
      value_cents:   12000 as Centavos,
      type:          'entrada',
      category:      'Diversos',
      date:          '2024-03-14',
      source:        'manual',
      fitId:         'manual-fit-1',
      importHash:    'existing-import-hash',
      uid,
      schemaVersion: 2,
    };
    const reconciledTx = makeTx({
      id:            existingId,
      _reconciled:   true,
      description:   'Supermercado X',
      value_cents:   7525 as Centavos,
      type:          'saida',
      category:      'Alimentação',
      date:          '2024-03-15',
      source:        'csv',
      fitId:         'csv-fit-2',
      schemaVersion: 2,
    });
    const onImport = vi.fn();

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await processResolvedImportBatch(uid, [reconciledTx] as any, onImport, [beforeTx]);

    expect(mockUpdateTransactionWithHistory).toHaveBeenCalledOnce();
    expect(onImport).not.toHaveBeenCalled();

    const updatePayload = mockUpdateTransactionWithHistory.mock.calls[0]?.[2] as Record<string, unknown>;
    expect(updatePayload).toEqual(expect.objectContaining({
      reconciliationStatus: 'reconciled',
      reconciliationSource: 'import',
      reconciledAt:         { _serverTimestamp: true },
      reconciledBy:         uid,
    }));

    const historyEvent = mockUpdateTransactionWithHistory.mock.calls[0]?.[3] as {
      before?: Record<string, unknown>;
      after?: Record<string, unknown>;
      changedFields?: string[];
      origin?: string;
      amount_cents?: number;
      category?: string;
    };

    expect(historyEvent).toMatchObject({
      origin:       'reconcile',
      amount_cents: 7525,
      category:     'Alimentação',
    });
    expect(historyEvent.changedFields).toEqual([
      'category',
      'description',
      'date',
      'type',
      'source',
      'value_cents',
      'fitId',
      'reconciliationStatus',
      'reconciliationSource',
      'reconciledAt',
      'reconciledBy',
    ]);
    expect(historyEvent.before).toEqual({
      category:             'Diversos',
      description:          'Compra manual',
      date:                 '2024-03-14',
      type:                 'entrada',
      source:               'manual',
      value_cents:          12000,
      fitId:                'manual-fit-1',
      reconciliationStatus: null,
      reconciliationSource: null,
      reconciledAt:         null,
      reconciledBy:         null,
    });
    expect(historyEvent.after).toEqual({
      category:             'Alimentação',
      description:          'Supermercado X',
      date:                 '2024-03-15',
      type:                 'saida',
      source:               'csv',
      value_cents:          7525,
      fitId:                'csv-fit-2',
      reconciliationStatus: 'reconciled',
      reconciliationSource: 'import',
      reconciledAt:         updatePayload['reconciledAt'],
      reconciledBy:         uid,
    });

    expect(historyEvent.changedFields).not.toEqual(expect.arrayContaining(['id', 'uid', 'importHash', 'value']));
    expect(historyEvent.before).not.toHaveProperty('id');
    expect(historyEvent.before).not.toHaveProperty('uid');
    expect(historyEvent.before).not.toHaveProperty('importHash');
    expect(historyEvent.before).not.toHaveProperty('value');
    expect(historyEvent.after).not.toHaveProperty('id');
    expect(historyEvent.after).not.toHaveProperty('uid');
    expect(historyEvent.after).not.toHaveProperty('importHash');
    expect(historyEvent.after).not.toHaveProperty('value');
  });

  it('sem uid: não chama updateTransaction nem lança erro', async () => {
    const reconciledTx = makeTx({ id: 'someDocId', _reconciled: true });
    const onImport     = vi.fn().mockResolvedValue({ added: 0 });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await expect(processResolvedImportBatch(undefined, [reconciledTx] as any, onImport)).resolves.not.toThrow();
    expect(mockUpdateTransactionWithHistory).not.toHaveBeenCalled();
  });
});
